version: "3.7"  # optional since v1.27.0
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    restart: always
    tty: true
    ports:
      - 5672:5672
      - 15672:15672

  inference:
    image: <IMAGE-ID>
    restart: always
    command: python application.py
    ports:
      - "6000:80"
    links:
      - rabbitmq:rabbitmq
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/%2F  
    volumes:
      - /var/data:/usr/src/app/data
    depends_on:
      - rabbitmq

  worker:
    image: <IMAGE-ID>
    restart: always
    command: python worker.py
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/%2F
    depends_on:
      - rabbitmq
      - inference
    links:
      - rabbitmq:rabbitmq
    volumes:
      - /var/data:/usr/src/app/data
